#!/bin/bash

usage(){
echo "
Written by Brian Bushnell
Last modified July 2, 2026

Description:  Grades mapping correctness of a sam file of synthetic reads
with headers generated by RandomReads3.java.  Compares mapped positions
against true positions encoded in read names.  Optionally compares CIGAR
strings against truth CIGARs (requires addcigar=t in randomreads.sh).

Usage:   gradesam.sh in=<sam file> reads=<number of reads>

Parameters:
in=<file>       Specify the input sam file, or stdin.
reads=<int>     Number of reads in mapper's input (i.e., the fastq file).
thresh=20       Max deviation from correct location to be considered
                'loosely correct'.
blasr=f         Set to 't' for BLASR output; fixes extra information
                added to read names.
quality=3       Reads with a mapping quality of this or below will be
                considered ambiguously mapped.
bitset=t        Track read ID's to detect secondary alignments.
                Necessary for mappers that incorrectly output multiple
                primary alignments per read.

CIGAR grading parameters:
fastq=<file>    Optional FASTQ file with truth CIGARs in headers
                (from randomreads.sh addcigar=t).  Enables comparison
                of alignment indels against known truth.
parsecigar=t    Enable CIGAR comparison when fastq is provided.

Please contact Brian Bushnell at bbushnell@lbl.gov if you encounter
any problems.
For documentation and the latest version, visit: https://bbmap.org
"
}

if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	usage
	exit
fi

resolveSymlinks(){
	SCRIPT="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
	while [ -h "$SCRIPT" ]; do
		DIR="$(dirname "$SCRIPT")"
		SCRIPT="$(readlink "$SCRIPT")"
		[ "${SCRIPT#/}" = "$SCRIPT" ] && SCRIPT="$DIR/$SCRIPT"
	done
	DIR="$(cd "$(dirname "$SCRIPT")" && pwd)"
	if [ -f "$DIR/bbtools.jar" ]; then
		CP="$DIR/bbtools.jar"
	else
		CP="$DIR/current/"
	fi
}

setEnv(){
	. "$DIR/javasetup.sh"
	. "$DIR/memdetect.sh"

	parseJavaArgs "--xmx=200m" "--xms=200m" "--mode=fixed" "$@"
	setEnvironment
}

launch() {
	CMD="java $EA $EOOM $SIMD $XMX $XMS -cp $CP align2.GradeSamFile $@"
	echo "$CMD" >&2
	eval $CMD
}

resolveSymlinks
setEnv "$@"
launch "$@"
