package prot;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.TreeMap;

/** Reviewed typed expected-copy producer; the family-only prototype is preserved separately. */
public final class MagQCExpectedCopyTableTyped {
	public static final String SCHEMA="expected_copy_table_v1";
	public static final String COUNT_SCHEMA="clean_typed_counts_v1";
	public static final String ROSTER_SCHEMA="clean_assembly_roster_v1";
	public static final String LAYOUT_SCHEMA="typed_item_layout_v1";
	public static final String COUNT_COLUMNS="unit_key\tgenome_id\ttid\titem_type\titem_key\tcopy_count";
	public static final String ROSTER_COLUMNS="unit_key\tgenome_id\tsource_rel\tsource_path\tinput_sha256\ttid\tdomain";
	public static final String LAYOUT_COLUMNS="item_type\titem_key\tfamily_id\tordinal";
	public static final String LABEL_COLUMNS="unit_key\tgenome_id\tsource_rel\tsource_path\tinput_sha256\tconfig_id\tsource\treference_id\tstatus\tlineage\tdomain\tphylum\tunknown_reason\tresult_sha256";
	public static final String TABLE_COLUMNS="context_type\tcontext_name\titem_type\titem_key\tmean_copy_count";
	public static final String[] NCRNA={"r16","r23","r5","rother","trna"};
	private static final String HEX="0123456789abcdef";
	private MagQCExpectedCopyTableTyped(){}
	public static void main(String[] args){if(args.length<1){fail("usage: build|validate key=value ...");}Map<String,String> p=new HashMap<String,String>();for(int i=1;i<args.length;i++){int eq=args[i].indexOf('=');if(eq<=0||p.put(args[i].substring(0,eq),args[i].substring(eq+1))!=null){fail("invalid/duplicate argument "+args[i]);}}if("build".equals(args[0])){build(required(p,"counts"),required(p,"roster"),required(p,"layout"),required(p,"labels"),required(p,"exclusions"),required(p,"out"));}else if("validate".equals(args[0])){load(required(p,"table"),required(p,"counts"),required(p,"roster"),required(p,"layout"),required(p,"labels"),required(p,"exclusions"));}else{fail("unknown command "+args[0]);}}

	public static final class Item {public final String type,key,familyId;public final int ordinal;Item(String t,String k,String f,int o){type=t;key=k;familyId=f;ordinal=o;}String id(){return type+"\t"+key;}}
	public static final class Population {public final String type,name;public final int denominator;private final double[] means;Population(String t,String n,int d,double[] m){type=t;name=n;denominator=d;means=m;}public double mean(int ordinal){if(ordinal<0||ordinal>=means.length){fail("item ordinal out of range");}return means[ordinal];}public double[] means(){return means.clone();}}
	public static final class Table {
		public final String counts,roster,layout,labels,exclusions,familyList;
		public final String countsHash,rosterHash,layoutHash,labelsHash,exclusionsHash,familyListHash;public final int eligibleAssemblyCount;
		public final Item[] items;private final TreeMap<String,Population> populations;
		Table(String c,String r,String l,String q,String x,String f,String ch,String rh,String lh,String qh,String xh,String fh,int n,Item[] i,TreeMap<String,Population> p){counts=c;roster=r;layout=l;labels=q;exclusions=x;familyList=f;countsHash=ch;rosterHash=rh;layoutHash=lh;labelsHash=qh;exclusionsHash=xh;familyListHash=fh;eligibleAssemblyCount=n;items=i;populations=p;}
		public Population population(String type,String name){Population p=populations.get(ctx(type,name));if(p==null){fail("missing population "+type+"/"+name);}return p;}
		public double expectation(String type,String name,String itemType,String itemKey){Population p=population(type,name);for(Item i:items){if(i.type.equals(itemType)&&i.key.equals(itemKey)){return p.mean(i.ordinal);}}fail("missing item "+itemType+"/"+itemKey);return 0;}
	}
	private static final class Assembly {final String unit,genome,rel,path,hash,domain;final int tid;Assembly(String u,String g,String r,String p,String h,int t,String d){unit=u;genome=g;rel=r;path=p;hash=h;tid=t;domain=d;}}
	private static final class Label {final String genome,rel,path,hash,status,phylum,source,reference;Label(String g,String r,String p,String h,String s,String y,String so,String re){genome=g;rel=r;path=p;hash=h;status=s;phylum=y;source=so;reference=re;}}
	private static final class Layout {final String familyPath,familyHash;final Item[] items;Layout(String p,String h,Item[] i){familyPath=p;familyHash=h;items=i;}}
	private static final class Sources {String counts,roster,layout,labels,exclusions,ch,rh,lh,qh,xh;Layout itemLayout;TreeMap<String,Assembly> assemblies;TreeMap<String,Label> labelRows;TreeMap<String,long[]> countRows;TreeMap<String,Population> pops;Sources(String c,String r,String l,String q,String x,String a,String b,String d,String e,String f,Layout z,TreeMap<String,Assembly> as,TreeMap<String,Label> ls,TreeMap<String,long[]> cs,TreeMap<String,Population> ps){counts=c;roster=r;layout=l;labels=q;exclusions=x;ch=a;rh=b;lh=d;qh=e;xh=f;itemLayout=z;assemblies=as;labelRows=ls;countRows=cs;pops=ps;}}

	public static Table build(String counts,String roster,String layout,String labels,String exclusions,String out){Sources s=sources(counts,roster,layout,labels,exclusions);write(out,s);return load(out,counts,roster,layout,labels,exclusions);}
	public static Table load(String table,String counts,String roster,String layout,String labels,String exclusions){Sources s=sources(counts,roster,layout,labels,exclusions);Table t=parseTable(table);if(!t.counts.equals(counts)||!t.roster.equals(roster)||!t.layout.equals(layout)||!t.labels.equals(labels)||!t.exclusions.equals(exclusions)||!t.familyList.equals(s.itemLayout.familyPath)){fail("provenance path mismatch");}if(!t.countsHash.equals(s.ch)||!t.rosterHash.equals(s.rh)||!t.layoutHash.equals(s.lh)||!t.labelsHash.equals(s.qh)||!t.exclusionsHash.equals(s.xh)||!t.familyListHash.equals(s.itemLayout.familyHash)){fail("provenance hash mismatch");}if(t.eligibleAssemblyCount!=s.assemblies.size()){fail("eligible assembly count mismatch");}compareItems(t.items,s.itemLayout.items);comparePops(t.populations,s.pops);return t;}
	/** Opens an ALREADY-BUILT table for a consumer. Verifies the caller's expected SHA-256 against the file bytes (streaming), then runs the same private self-consistency parser that load uses (schema, metadata lines, columns, identical item order across populations, denominator/header agreement). Does NOT revalidate the five source artifacts named in the header: those are bound at build/load time only; a consumer binds OUTWARD to its bundle by hash (family_list_sha256), never inward to sources. */
	public static Table open(String table,String expectedTableSha256){if(expectedTableSha256==null||!expectedTableSha256.matches("[0-9a-f]{64}")){fail("invalid expected table hash");}String actual=sha(table);if(!actual.equals(expectedTableSha256)){fail("table hash mismatch: expected "+expectedTableSha256+" actual "+actual);}return parseTable(table);}

	private static Sources sources(String cf,String rf,String lf,String qf,String xf){Layout z=readLayout(lf);HashSet<Integer> excluded=readExclusions(xf);TreeMap<String,Assembly> as=readRoster(rf,excluded);TreeMap<String,Label> ls=readLabels(qf,as,excluded);TreeMap<String,long[]> cs=readCounts(cf,as,z.items);TreeMap<String,Population> ps=new TreeMap<String,Population>();ps.put(ctx("global","-"),population("global","-",as.keySet(),cs,z.items));TreeMap<String,ArrayList<String>> byPhylum=new TreeMap<String,ArrayList<String>>();for(String u:as.keySet()){Label l=ls.get(u);if("classified".equals(l.status)){ArrayList<String> m=byPhylum.get(l.phylum);if(m==null){m=new ArrayList<String>();byPhylum.put(l.phylum,m);}m.add(u);}}for(Map.Entry<String,ArrayList<String>> e:byPhylum.entrySet()){ps.put(ctx("phylum",e.getKey()),population("phylum",e.getKey(),e.getValue(),cs,z.items));}return new Sources(cf,rf,lf,qf,xf,sha(cf),sha(rf),sha(lf),sha(qf),sha(xf),z,as,ls,cs,ps);}
	private static Population population(String type,String name,Iterable<String> units,TreeMap<String,long[]> rows,Item[] items){ArrayList<String> sorted=new ArrayList<String>();for(String u:units){sorted.add(u);}java.util.Collections.sort(sorted);if(sorted.isEmpty()){fail("empty population "+type+"/"+name);}long[] sum=new long[items.length];for(String u:sorted){long[] row=rows.get(u);if(row==null){fail("missing count row "+u);}for(int i=0;i<row.length;i++){if(Long.MAX_VALUE-sum[i]<row[i]){fail("count overflow at item "+i);}sum[i]+=row[i];}}double[] means=new double[items.length];for(int i=0;i<sum.length;i++){means[i]=((double)sum[i])/sorted.size();if(Double.isInfinite(means[i])||Double.isNaN(means[i])){fail("nonfinite mean");}}return new Population(type,name,sorted.size(),means);}

	private static Layout readLayout(String file){String schema=null,fp=null,fh=null,cols=null;ArrayList<Item> out=new ArrayList<Item>();try(BufferedReader br=reader(file)){for(String line;(line=br.readLine())!=null;){if(line.length()==0){continue;}if(line.charAt(0)=='#'){String[] p=line.split("\\t",-1);if(line.startsWith("#schema_version\t")){if(p.length!=2||schema!=null||!LAYOUT_SCHEMA.equals(p[1])){fail("invalid layout schema");}schema=p[1];}else if(line.startsWith("#family_list\t")){if(fp!=null||p.length!=5||!"#".equals(p[2])||!"sha256".equals(p[3])||!p[4].matches("[0-9a-f]{64}")){fail("invalid family metadata");}fp=p[1];fh=p[4];}else if(line.startsWith("#columns\t")){String c=line.substring(9);if(cols!=null||!LAYOUT_COLUMNS.equals(c)){fail("invalid layout columns");}cols=c;}else{fail("unknown layout metadata");}}else{String[] p=fields(line,4,file);int o=nonneg(p[3],"ordinal",file);if(o!=out.size()){fail("layout ordinal/order mismatch");}if(!"P".equals(p[0])&&!"N".equals(p[0])){fail("invalid item type");}safe(p[0],"item_type",file);safe(p[1],"item_key",file);safe(p[2],"family_id",file);out.add(new Item(p[0],p[1],p[2],o));}}}catch(IOException e){throw new RuntimeException(e);}if(!LAYOUT_SCHEMA.equals(schema)||fp==null||cols==null||out.isEmpty()||!sha(fp).equals(fh)){fail("incomplete/layout family hash mismatch");}String[] families=readFamily(fp);HashSet<String> seen=new HashSet<String>();int p=0;for(Item i:out){if(!seen.add(i.id())){fail("duplicate item "+i.id());}if("P".equals(i.type)){if(i.ordinal!=p||!i.key.equals(Integer.toString(p))||!i.familyId.equals(families.length>p?families[p]:"")){fail("family item/layout mismatch at "+p);}p++;}}if(p!=families.length||out.size()!=p+NCRNA.length){fail("layout must contain all P ranks and five N items");}for(int i=0;i<NCRNA.length;i++){Item x=out.get(p+i);if(!"N".equals(x.type)||!NCRNA[i].equals(x.key)||!"-".equals(x.familyId)){fail("ncRNA item order mismatch");}}return new Layout(fp,fh,out.toArray(new Item[out.size()]));}
	private static String[] readFamily(String file){ArrayList<String> out=new ArrayList<String>();HashSet<String> seen=new HashSet<String>();try(BufferedReader br=reader(file)){boolean h=false;for(String line;(line=br.readLine())!=null;){if(line.length()==0){continue;}if(!h){if(!"#rank\trep_id\tocc_total".equals(line)){fail("invalid family columns");}h=true;continue;}String[] p=fields(line,3,file);int r=nonneg(p[0],"family rank",file);nonneg(p[2],"family occurrence total",file);if(r!=out.size()||!seen.add(p[1])){fail("family order/duplicate");}safe(p[1],"family id",file);out.add(p[1]);}if(!h||out.isEmpty()){fail("empty family list");}}catch(IOException e){throw new RuntimeException(e);}return out.toArray(new String[out.size()]);}
	private static HashSet<Integer> readExclusions(String file){HashSet<Integer> out=new HashSet<Integer>();try(BufferedReader br=reader(file)){boolean h=false;for(String line;(line=br.readLine())!=null;){if(line.length()==0){continue;}if(line.charAt(0)=='#'){if("#excluded_tid\tclass\treason".equals(line)){h=true;}continue;}String[] p=fields(line,3,file);int tid=nonneg(p[0],"excluded tid",file);if(!out.add(tid)){fail("duplicate exclusion tid");}safe(p[1],"exclusion class",file);safe(p[2],"exclusion reason",file);}if(!h){fail("missing exclusion header");}}catch(IOException e){throw new RuntimeException(e);}return out;}
	private static TreeMap<String,Assembly> readRoster(String file,HashSet<Integer> excluded){TreeMap<String,Assembly> out=new TreeMap<String,Assembly>();HashSet<String> gs=new HashSet<String>(),rs=new HashSet<String>();HashSet<Integer> ts=new HashSet<Integer>();try(BufferedReader br=reader(file)){boolean schema=false,cols=false;for(String line;(line=br.readLine())!=null;){if(line.length()==0){continue;}if(line.charAt(0)=='#'){if(("#schema_version\t"+ROSTER_SCHEMA).equals(line)){schema=true;}if(("#columns\t"+ROSTER_COLUMNS).equals(line)){cols=true;}continue;}String[] p=fields(line,7,file);safe(p[0],"unit",file);safe(p[1],"genome",file);safe(p[2],"source_rel",file);safe(p[3],"source_path",file);if(!p[0].equals(unitKey(p[2]))||!p[1].equals("genome_"+p[0])){fail("roster unit/genome does not bind source_rel");}if(!p[4].matches("[0-9a-f]{64}")){fail("invalid roster hash");}int t=nonneg(p[5],"tid",file);safe(p[6],"domain",file);if(excluded.contains(t)||!gs.add(p[1])||!rs.add(p[2])||!ts.add(t)||out.put(p[0],new Assembly(p[0],p[1],p[2],p[3],p[4],t,p[6]))!=null){fail("invalid/duplicate clean roster row");}}if(!schema||!cols||out.isEmpty()){fail("invalid/empty roster");}}catch(IOException e){throw new RuntimeException(e);}return out;}
	private static int labelTid(String rel){int slash=rel.lastIndexOf('/');String b=slash<0?rel:rel.substring(slash+1);if(!b.startsWith("tid_")){fail("label source_rel lacks tid: "+rel);}int end=b.indexOf('_',4);if(end<5){fail("label source_rel malformed: "+rel);}return nonneg(b.substring(4,end),"label tid",rel);}
	private static TreeMap<String,Label> readLabels(String file,TreeMap<String,Assembly> roster,HashSet<Integer> excluded){TreeMap<String,Label> out=new TreeMap<String,Label>();HashSet<Integer> labelTids=new HashSet<Integer>();try(BufferedReader br=reader(file)){boolean cols=false;for(String line;(line=br.readLine())!=null;){if(line.length()==0){continue;}if(line.charAt(0)=='#'){if(("#columns\t"+LABEL_COLUMNS).equals(line)){cols=true;}continue;}String[] p=fields(line,14,file);int tid=labelTid(p[2]);if(!labelTids.add(tid)){fail("duplicate label tid "+tid);}Assembly a=roster.get(p[0]);if(a==null&&!excluded.contains(tid)){fail("label unit is neither clean roster nor excluded: "+p[0]);}if(a!=null&&(!a.genome.equals(p[1])||!a.rel.equals(p[2])||!a.path.equals(p[3])||!a.hash.equals(p[4])||a.tid!=tid||(("classified".equals(p[8])||"partial".equals(p[8]))&&!a.domain.equals(p[10])))){fail("label/roster mismatch: "+p[0]);}if(!"server".equals(p[6])||p[7].length()==0||"unknown".equals(p[7])){fail("label source/reference invalid");}if(!"classified".equals(p[8])&&!"partial".equals(p[8])&&!"unknown".equals(p[8])){fail("invalid label status");}if("unknown".equals(p[8])&&!"unknown".equals(p[10])){fail("unknown label domain must be unknown");}if("classified".equals(p[8])&&("unknown".equals(p[11])||p[11].length()==0)){fail("classified label phylum invalid");}if(("partial".equals(p[8])||"unknown".equals(p[8]))&&!"unknown".equals(p[11])){fail("partial/unknown phylum invalid");}if(!p[4].matches("[0-9a-f]{64}")||!p[13].matches("[0-9a-f]{64}")){fail("invalid label hash");}if(out.put(p[0],new Label(p[1],p[2],p[3],p[4],p[8],p[11],p[6],p[7]))!=null){fail("duplicate label unit");}}if(!cols||out.isEmpty()){fail("invalid/empty labels");}}catch(IOException e){throw new RuntimeException(e);}for(String u:roster.keySet()){if(!out.containsKey(u)){fail("missing clean label "+u);}}return out;}
	private static TreeMap<String,long[]> readCounts(String file,TreeMap<String,Assembly> roster,Item[] items){HashMap<String,Integer> ord=new HashMap<String,Integer>();for(Item i:items){ord.put(i.id(),i.ordinal);}TreeMap<String,long[]> out=new TreeMap<String,long[]>();HashSet<String> seen=new HashSet<String>();try(BufferedReader br=reader(file)){boolean schema=false,cols=false;for(String line;(line=br.readLine())!=null;){if(line.length()==0){continue;}if(line.charAt(0)=='#'){if(("#schema_version\t"+COUNT_SCHEMA).equals(line)){schema=true;}if(("#columns\t"+COUNT_COLUMNS).equals(line)){cols=true;}continue;}String[] p=fields(line,6,file);Assembly a=roster.get(p[0]);if(a==null||!a.genome.equals(p[1])||a.tid!=nonneg(p[2],"count tid",file)){fail("count/roster mismatch");}String id=p[3]+"\t"+p[4];Integer o=ord.get(id);if(o==null){fail("count item absent from layout: "+id);}if(!seen.add(p[0]+"\t"+id)){fail("duplicate count row");}long value=nonnegLong(p[5],"copy count",file);long[] row=out.get(p[0]);if(row==null){row=new long[items.length];out.put(p[0],row);}row[o.intValue()]=value;}if(!schema||!cols){fail("invalid count headers");}}catch(IOException e){throw new RuntimeException(e);}for(String u:roster.keySet()){if(!out.containsKey(u)){fail("missing count assembly "+u);}for(Item i:items){if("N".equals(i.type)&&!seen.contains(u+"\t"+i.id())){fail("missing ncRNA item "+u+"/"+i.id());}}}return out;}
	private static Table parseTable(String file){
		String schema=null,counts=null,roster=null,layout=null,labels=null,exclusions=null,family=null,ch=null,rh=null,lh=null,qh=null,xh=null,fh=null,columns=null;int eligible=-1,itemCount=-1;
		TreeMap<String,Integer> denominators=new TreeMap<String,Integer>();ArrayList<String[]> rows=new ArrayList<String[]>();
		try(BufferedReader br=reader(file)){for(String line;(line=br.readLine())!=null;){if(line.length()==0){continue;}if(line.charAt(0)=='#'){
			String[] p=line.split("\\t",-1);
			if(line.startsWith("#schema_version\t")){if(p.length!=2||schema!=null||!SCHEMA.equals(p[1])){fail("invalid table schema");}schema=p[1];}
			else if(line.startsWith("#typed_count_artifact\t")){if(counts!=null){fail("duplicate count metadata");}String[] z=meta(p,"typed_count_artifact");counts=z[0];ch=z[1];}
			else if(line.startsWith("#clean_assembly_roster\t")){if(roster!=null){fail("duplicate roster metadata");}String[] z=meta(p,"clean_assembly_roster");roster=z[0];rh=z[1];}
			else if(line.startsWith("#typed_item_layout\t")){if(layout!=null){fail("duplicate layout metadata");}String[] z=meta(p,"typed_item_layout");layout=z[0];lh=z[1];}
			else if(line.startsWith("#quickclade_labels\t")){if(labels!=null){fail("duplicate label metadata");}String[] z=meta(p,"quickclade_labels");labels=z[0];qh=z[1];}
			else if(line.startsWith("#exclusion_ledger\t")){if(exclusions!=null){fail("duplicate exclusion metadata");}String[] z=meta(p,"exclusion_ledger");exclusions=z[0];xh=z[1];}
			else if(line.startsWith("#family_list\t")){if(family!=null){fail("duplicate family metadata");}String[] z=meta(p,"family_list");family=z[0];fh=z[1];}
			else if(line.startsWith("#population\t")){if(p.length!=4||!("global".equals(p[1])||"phylum".equals(p[1]))){fail("invalid population metadata");}safe(p[2],"population name",file);if(denominators.put(ctx(p[1],p[2]),positive(p[3],"denominator",file))!=null){fail("duplicate population metadata");}}
			else if(line.startsWith("#columns\t")){String c=line.substring(9);if(columns!=null||!TABLE_COLUMNS.equals(c)){fail("invalid table columns");}columns=c;}
			else if(line.startsWith("#eligible_assembly_count\t")){if(eligible>=0||p.length!=2){fail("invalid eligible assembly metadata");}eligible=nonneg(p[1],"eligible assembly count",file);}
			else if(line.startsWith("#item_count\t")){if(itemCount>=0||p.length!=2){fail("invalid item count metadata");}itemCount=positive(p[1],"item count",file);}
			else{fail("unknown table metadata: "+line);}
		}else{if(schema==null||columns==null){fail("table data precedes headers");}rows.add(fields(line,5,file));}}}catch(IOException e){throw new RuntimeException(e);}
		if(!SCHEMA.equals(schema)||counts==null||roster==null||layout==null||labels==null||exclusions==null||family==null||columns==null||eligible<0||itemCount<0){fail("incomplete table headers");}
		TreeMap<String,ArrayList<String[]>> byPop=new TreeMap<String,ArrayList<String[]>>();HashSet<String> seen=new HashSet<String>();for(String[] p:rows){if(!("global".equals(p[0])||"phylum".equals(p[0]))){fail("invalid table context");}safe(p[1],"context name",file);if("global".equals(p[0])&&!"-".equals(p[1])){fail("global context name must be '-'");}if(!("P".equals(p[2])||"N".equals(p[2]))){fail("invalid table item type");}safe(p[3],"item key",file);finite(p[4],"mean",file);String c=ctx(p[0],p[1]);String k=c+"\t"+p[2]+"\t"+p[3];if(!seen.add(k)){fail("duplicate table row "+k);}ArrayList<String[]> a=byPop.get(c);if(a==null){a=new ArrayList<String[]>();byPop.put(c,a);}a.add(p);}
		if(!byPop.keySet().equals(denominators.keySet())||denominators.isEmpty()){fail("population data/header mismatch");}ArrayList<Item> itemList=new ArrayList<Item>();HashSet<String> itemIds=new HashSet<String>();TreeMap<String,Population> pops=new TreeMap<String,Population>();
		for(Map.Entry<String,Integer> e:denominators.entrySet()){ArrayList<String[]> a=byPop.get(e.getKey());if(a==null||a.isEmpty()){fail("missing population data "+e.getKey());}if(itemList.isEmpty()){for(int i=0;i<a.size();i++){String id=a.get(i)[2]+"\t"+a.get(i)[3];if(!itemIds.add(id)){fail("duplicate table item "+id);}itemList.add(new Item(a.get(i)[2],a.get(i)[3],"-",i));}}else if(a.size()!=itemList.size()){fail("population item count mismatch");}double[] means=new double[itemList.size()];for(int i=0;i<a.size();i++){String[] p=a.get(i);Item item=itemList.get(i);if(!item.type.equals(p[2])||!item.key.equals(p[3])){fail("population item order mismatch");}means[i]=finite(p[4],"mean",file);}int tab=e.getKey().indexOf('\t');pops.put(e.getKey(),new Population(e.getKey().substring(0,tab),e.getKey().substring(tab+1),e.getValue(),means));}
		if(itemList.size()!=itemCount){fail("item count metadata mismatch");}return new Table(counts,roster,layout,labels,exclusions,family,ch,rh,lh,qh,xh,fh,eligible,itemList.toArray(new Item[itemList.size()]),pops);
	}
	private static void write(String file,Sources s){try(BufferedWriter bw=writer(file)){bw.write("#schema_version\t"+SCHEMA+"\n");metaLine(bw,"typed_count_artifact",s.counts,s.ch);metaLine(bw,"clean_assembly_roster",s.roster,s.rh);metaLine(bw,"typed_item_layout",s.layout,s.lh);metaLine(bw,"quickclade_labels",s.labels,s.qh);metaLine(bw,"exclusion_ledger",s.exclusions,s.xh);metaLine(bw,"family_list",s.itemLayout.familyPath,s.itemLayout.familyHash);bw.write("#eligible_assembly_count\t"+s.assemblies.size()+"\n#item_count\t"+s.itemLayout.items.length+"\n");for(Population p:s.pops.values()){bw.write("#population\t"+p.type+"\t"+p.name+"\t"+p.denominator+"\n");}bw.write("#columns\t"+TABLE_COLUMNS+"\n");for(Population p:s.pops.values()){for(Item i:s.itemLayout.items){bw.write(p.type+"\t"+p.name+"\t"+i.type+"\t"+i.key+"\t"+Double.toString(p.mean(i.ordinal))+"\n");}}}catch(IOException e){throw new RuntimeException(e);}}
	private static void metaLine(BufferedWriter bw,String name,String path,String hash)throws IOException{bw.write("#"+name+"\t"+path+"\t#\tsha256\t"+hash+"\n");}
	private static String[] meta(String[] p,String name){if(p.length!=5||!"#".equals(p[2])||!"sha256".equals(p[3])||!p[4].matches("[0-9a-f]{64}")){fail("invalid "+name+" metadata");}safe(p[1],name+" path",name);return new String[]{p[1],p[4]};}
	private static void compareItems(Item[] actual,Item[] expected){if(actual.length!=expected.length){fail("item count mismatch");}for(int i=0;i<expected.length;i++){if(!actual[i].id().equals(expected[i].id())){fail("item order mismatch at "+i);}}}
	private static void comparePops(TreeMap<String,Population> actual,TreeMap<String,Population> expected){if(!actual.keySet().equals(expected.keySet())){fail("population context mismatch");}for(String k:expected.keySet()){Population a=actual.get(k),e=expected.get(k);if(a.denominator!=e.denominator||a.means.length!=e.means.length){fail("population shape mismatch "+k);}for(int i=0;i<e.means.length;i++){if(Double.doubleToLongBits(a.means[i])!=Double.doubleToLongBits(e.means[i])){fail("population mean mismatch "+k+" item "+i);}}}}
	private static BufferedReader reader(String f)throws IOException{return new BufferedReader(new InputStreamReader(new FileInputStream(f),StandardCharsets.UTF_8));}
	private static BufferedWriter writer(String f)throws IOException{return new BufferedWriter(new OutputStreamWriter(new FileOutputStream(f),StandardCharsets.UTF_8));}
	private static String[] fields(String line,int n,String file){String[] p=line.split("\t",-1);if(p.length!=n){fail("expected "+n+" fields in "+file+", got "+p.length);}return p;}
	private static void safe(String s,String n,String f){if(s.length()==0||s.indexOf('\t')>=0||s.indexOf('\r')>=0||s.indexOf('\n')>=0){fail("invalid "+n+" in "+f);}}
	private static int nonneg(String s,String n,String f){try{int x=Integer.parseInt(s);if(x<0){fail("negative "+n+" in "+f);}return x;}catch(Exception e){fail("invalid "+n+" in "+f);return -1;}}
	private static String required(Map<String,String> p,String key){String value=p.get(key);if(value==null||value.length()==0){fail("missing "+key);}return value;}
	private static int positive(String s,String n,String f){int x=nonneg(s,n,f);if(x<=0){fail("nonpositive "+n+" in "+f);}return x;}
	private static long nonnegLong(String s,String n,String f){try{long x=Long.parseLong(s);if(x<0){fail("negative "+n+" in "+f);}return x;}catch(Exception e){fail("invalid "+n+" in "+f);return -1;}}
	private static double finite(String s,String n,String f){try{double x=Double.parseDouble(s);if(x<0||Double.isNaN(x)||Double.isInfinite(x)){fail("invalid "+n+" in "+f);}return x;}catch(Exception e){fail("invalid "+n+" in "+f);return -1;}}
	private static String ctx(String type,String name){return type+"\t"+name;}
	private static String unitKey(String sourceRel){return "g_"+shaText(sourceRel+"\n");}
	private static String shaText(String value){try{byte[] d=MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8));StringBuilder b=new StringBuilder(64);for(byte x:d){b.append(HEX.charAt((x>>>4)&15)).append(HEX.charAt(x&15));}return b.toString();}catch(NoSuchAlgorithmException e){throw new RuntimeException(e);}}
	private static String sha(String file){try{MessageDigest md=MessageDigest.getInstance("SHA-256");try(FileInputStream in=new FileInputStream(file)){byte[] buf=new byte[65536];for(int n;(n=in.read(buf))!=-1;){md.update(buf,0,n);}}byte[] d=md.digest();StringBuilder b=new StringBuilder(64);for(byte x:d){b.append(HEX.charAt((x>>>4)&15)).append(HEX.charAt(x&15));}return b.toString();}catch(IOException e){throw new RuntimeException(e);}catch(NoSuchAlgorithmException e){throw new RuntimeException(e);}}
	private static void fail(String message){throw new IllegalArgumentException(message);}
}
